version: '3.8'
services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: studs
      POSTGRES_PASSWORD: studs
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    build: ./backend
    depends_on:
      - pg
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/studs
      SPRING_DATASOURCE_USERNAME: studs
      SPRING_DATASOURCE_PASSWORD: studs
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"   
    depends_on:
      - backend

volumes:
  pgdata:
