spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/studs
#    url: jdbc:postgresql://pg:5434/studs
    username: studs
    password: studs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: messages
  web:
    locale: en
    locale-resolver: fixed
server:
  port: 8080
