spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/studs
#    url: jdbc:postgresql://pg:5434/studs
    username: studs
    password: studs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
