name: CI/CD Pipeline

on:
  push:
    branches:
      - feature
  pull_request:

jobs:
  build-and-test:
    name: Build and Test Backend & Frontend
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Backend
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build and Test Backend
        working-directory: ./backend
        run: mvn clean verify -DskipTests

      # Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend_jar
          path: backend/target/*.jar

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend_dist
          path: frontend/dist/**

  deploy:
    name: Deploy to Server
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend_jar
          path: backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend_dist
          path: frontend_temp

      - name: Prepare frontend files
        run: |
          # Создаем папку для финальных файлов
          mkdir -p frontend_final
          # Копируем все содержимое из frontend_temp во frontend_final
          cp -r frontend_temp/* frontend_final/
          echo "Frontend files prepared:"
          ls -la frontend_final/

      - name: Show artifacts (debug)
        run: |
          echo "Backend artifact:"
          ls -la backend || true
          echo "Frontend temp:"
          ls -la frontend_temp || true
          echo "Frontend final:"
          ls -la frontend_final || true

      - name: Upload backend jar to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "backend/*"
          target: "${{ secrets.DEPLOY_PATH }}/backend/upload"

      - name: Upload frontend dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "frontend_final/*"
          target: "${{ secrets.DEPLOY_PATH }}/../public_html"